server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: kitchen-route
              uri: http://localhost:8081
              predicates:
                - Path=/order/**
              filters:
                - StripPrefix=1
                - AddRequestHeader=X-Hotel-Source, Gateway-Entrance # <--- Real world tracking