version: '3.8'

services:
  eureka-server:
    build: ./Queue-Eureka-Server
    container_name: eureka-server
    ports:
      - "8761:8761"
    restart: always
    networks:
      - microservices-net

  api-gateway:
    build: .
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
