name: Deploy API Gateway v2.0

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: Build API Gateway
        run: mvn clean package -DskipTests

      - name: Copy Gateway to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: "3.81.73.232"
          username: "ubuntu"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "target/*.jar,Dockerfile"
          target: "~/app/API-Gatway"

      - name: SSH and Restart Gateway
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "3.81.73.232"
          username: "ubuntu"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/app/API-Gatway

            echo "Remove old Docker container..."
            sudo docker rm -f api-gateway || true

            echo "Show who uses 8080 before killing..."
            sudo lsof -i :8080 || true

            echo "Kill process using 8080..."
            PID=$(sudo lsof -t -i:8080 || true)
            if [ -n "$PID" ]; then
              echo "Killing PID: $PID"
              sudo kill -9 $PID || true
            fi
 
            sleep 3

            echo "Check 8080 again..."
            sudo lsof -i :8080 || true

            echo "If port is still used, stop deploy..."
            if sudo lsof -i :8080; then
              echo "ERROR: Port 8080 is still used. Something restarted automatically."
              ps -fp $(sudo lsof -t -i:8080) || true
              exit 1
            fi

            echo "Build image..."
            sudo docker build -t api-gateway .

            echo "Run api-gateway..."
            sudo docker run -d \
              --name api-gateway \
              --restart unless-stopped \
              -p 8080:8080 \
              api-gateway

            sudo docker ps
            sudo docker logs --tail=80 api-gateway